mapRoles: |
  - rolearn: arn:aws:iam::488770167024:role/eks-node-group-role
    username: system:node:{{EC2PrivateDNSName}}
    groups:
      - system:bootstrappers
      - system:nodes
  - rolearn: arn:aws:iam::488770167024:role/service-role/codebuild-cloud-ai-demo-infra-service-role
    username: build
    groups:
      - system:masters

mapUsers: |
  - userarn: arn:aws:iam::488770167024:user/jeremywang
    username: jeremywang
    groups:
      - system:masters



